ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v10.11.0'
    hooks:
      - id: eslint
        additional_dependencies:
            - "eslint"
            - "@eslint/js"
            - "globals"

